/**
 * Dummy Ticket Data for SheetDB Population
 */

import { CreateTicketData } from "./sheetdb";

export const dummyTicketsData: CreateTicketData[] = [
  {
    userId: "u1",
    userName: "Rajesh Kumar",
    userMobile: "9876543210",
    userEmail: "rajesh.kumar@gmail.com",
    district: "Ranchi",
    site: "Kanke Village",
    dueDate: "2024-02-15",
    issueDescription: "Solar Pump - Kanke: Pump not working since morning. Motor makes unusual noise.",
    priority: "high",
    contractor: "Green Energy Solutions",
    deviceId: "d1",
    deviceType: "solar_pump",
  },
  {
    userId: "u2",
    userName: "Priya Devi",
    userMobile: "9876543211",
    userEmail: "priya.devi@gmail.com",
    district: "Dhanbad",
    site: "Jharia Town",
    dueDate: "2024-02-10",
    issueDescription: "Rooftop Solar - Jharia: Inverter showing error code E05. Power output reduced by 50%.",
    priority: "medium",
    contractor: "NA",
    deviceId: "d3",
    deviceType: "rooftop_solar",
  },
  {
    userId: "u3",
    userName: "Amit Singh",
    userMobile: "9876543212",
    userEmail: "amit.singh@gmail.com",
    district: "Bokaro",
    site: "Sector 4",
    dueDate: "2024-02-08",
    issueDescription: "Mini Grid - Sector 4: Frequent power fluctuations affecting connected households.",
    priority: "critical",
    contractor: "Solar Tech India",
    deviceId: "d6",
    deviceType: "mini_grid",
  },
  {
    userId: "u2",
    userName: "Priya Devi",
    userMobile: "9876543211",
    userEmail: "priya.devi@gmail.com",
    district: "Dhanbad",
    site: "Govindpur",
    dueDate: "2024-02-05",
    issueDescription: "High Mast - Govindpur: All lights not working. Complete failure.",
    priority: "high",
    contractor: "NA",
    deviceId: "d4",
    deviceType: "high_mast",
  },
  {
    userId: "u1",
    userName: "Rajesh Kumar",
    userMobile: "9876543210",
    userEmail: "rajesh.kumar@gmail.com",
    district: "Ranchi",
    site: "Ratu Block",
    dueDate: "2024-02-20",
    issueDescription: "Mini Grid - Ratu: Request for capacity upgrade. Current system insufficient for village needs.",
    priority: "low",
    contractor: "Green Energy Solutions",
    deviceId: "d2",
    deviceType: "mini_grid",
  },
  {
    userId: "u4",
    userName: "Sita Devi",
    userMobile: "9876543213",
    userEmail: "sita.devi@gmail.com",
    district: "Hazaribagh",
    site: "Ramgarh Road",
    dueDate: "2024-02-12",
    issueDescription: "Street Light - Ramgarh: LED panel damaged, needs replacement.",
    priority: "medium",
    contractor: "Eco Power Systems",
    deviceId: "d7",
    deviceType: "street_light",
  },
  {
    userId: "u5",
    userName: "Mohan Prasad",
    userMobile: "9876543214",
    userEmail: "mohan.prasad@gmail.com",
    district: "Giridih",
    site: "Giridih Town",
    dueDate: "2024-02-18",
    issueDescription: "Solar Pump - Giridih: Battery not charging properly. Voltage dropping frequently.",
    priority: "high",
    contractor: "Sunrise Energy",
    deviceId: "d8",
    deviceType: "solar_pump",
  },
  {
    userId: "u6",
    userName: "Lakshmi Oraon",
    userMobile: "9876543215",
    userEmail: "lakshmi.oraon@gmail.com",
    district: "Deoghar",
    site: "Baba Dham",
    dueDate: "2024-02-22",
    issueDescription: "Rooftop Solar - Deoghar: Solar panels covered with dust and debris. Cleaning required.",
    priority: "low",
    contractor: "Green Energy Solutions",
    deviceId: "d9",
    deviceType: "rooftop_solar",
  },
  {
    userId: "u7",
    userName: "Birsa Munda",
    userMobile: "9876543216",
    userEmail: "birsa.munda@gmail.com",
    district: "Dumka",
    site: "Dumka Town",
    dueDate: "2024-02-25",
    issueDescription: "Mini Grid - Dumka: Connection wire damaged by animals. Immediate repair needed.",
    priority: "critical",
    contractor: "Solar Tech India",
    deviceId: "d10",
    deviceType: "mini_grid",
  },
  {
    userId: "u8",
    userName: "Dhananjay Ray",
    userMobile: "9876543217",
    userEmail: "dhananjay.ray@gmail.com",
    district: "Jamshedpur",
    site: "Morabadi",
    dueDate: "2024-02-28",
    issueDescription: "Controller - Morabadi: Controller malfunctioning. Display showing wrong values.",
    priority: "medium",
    contractor: "NA",
    deviceId: "d11",
    deviceType: "solar_pump",
  },
  {
    userId: "u9",
    userName: "Sunita Soren",
    userMobile: "9876543218",
    userEmail: "sunita.soren@gmail.com",
    district: "Simdega",
    site: "Simdega Town",
    dueDate: "2024-03-01",
    issueDescription: "High Mast - Simdega: Water level sensor not working. Automatic switch failing.",
    priority: "high",
    contractor: "Eco Power Systems",
    deviceId: "d12",
    deviceType: "high_mast",
  },
  {
    userId: "u10",
    userName: "Vikram Kumar",
    userMobile: "9876543219",
    userEmail: "vikram.kumar@gmail.com",
    district: "Palamu",
    site: "Daltonganj",
    dueDate: "2024-03-05",
    issueDescription: "Street Light - Daltonganj: Multiple lights flickering intermittently.",
    priority: "low",
    contractor: "Sunrise Energy",
    deviceId: "d13",
    deviceType: "street_light",
  },
  {
    userId: "u11",
    userName: "Anita Devi",
    userMobile: "9876543220",
    userEmail: "anita.devi@gmail.com",
    district: "Latehar",
    site: "Latehar Town",
    dueDate: "2024-03-08",
    issueDescription: "Rooftop Solar - Latehar: Inverter making buzzing noise. Safety concern.",
    priority: "high",
    contractor: "Green Energy Solutions",
    deviceId: "d14",
    deviceType: "rooftop_solar",
  },
  {
    userId: "u12",
    userName: "Rahul Mehta",
    userMobile: "9876543221",
    userEmail: "rahul.mehta@gmail.com",
    district: "Gumla",
    site: "Gumla Town",
    dueDate: "2024-03-10",
    issueDescription: "Mini Grid - Gumla: Power outage in entire grid. No power since yesterday.",
    priority: "critical",
    contractor: "Solar Tech India",
    deviceId: "d15",
    deviceType: "mini_grid",
  },
  {
    userId: "u13",
    userName: "Pooja Kumari",
    userMobile: "9876543222",
    userEmail: "pooja.kumari@gmail.com",
    district: "Chaibasa",
    site: "Chaibasa Town",
    dueDate: "2024-03-12",
    issueDescription: "Solar Pump - Chaibasa: Low water discharge. Previously 200 L/min, now only 80 L/min.",
    priority: "medium",
    contractor: "NA",
    deviceId: "d16",
    deviceType: "solar_pump",
  },
];

export function generateMoreDummyTickets(count: number): CreateTicketData[] {
  // User to district mapping - each user has a specific district
  const userDistrictMap: Record<string, string> = {
    "u1": "Ranchi",
    "u2": "Dhanbad",
    "u3": "Bokaro",
    "u4": "Hazaribagh",
    "u5": "Giridih",
    "u6": "Deoghar",
    "u7": "Dumka",
    "u8": "Jamshedpur",
    "u9": "Simdega",
    "u10": "Palamu",
    "u11": "Latehar",
    "u12": "Gumla",
    "u13": "Chaibasa",
    "u14": "Ranchi",
    "u15": "Dhanbad",
    "u16": "Bokaro",
    "u17": "Hazaribagh",
    "u18": "Giridih",
    "u19": "Deoghar",
    "u20": "Dumka",
    "u21": "Ranchi",
    "u22": "Dhanbad",
    "u23": "Bokaro",
    "u24": "Hazaribagh",
    "u25": "Giridih",
    "u26": "Deoghar",
    "u27": "Dumka",
    "u28": "Jamshedpur",
    "u29": "Simdega",
    "u30": "Palamu",
    "u31": "Latehar",
    "u32": "Gumla",
    "u33": "Chaibasa",
    "u34": "Ranchi",
    "u35": "Dhanbad",
    "u36": "Bokaro",
    "u37": "Hazaribagh",
    "u38": "Giridih",
    "u39": "Deoghar",
    "u40": "Dumka",
    "u41": "Ranchi",
    "u42": "Dhanbad",
    "u43": "Bokaro",
    "u44": "Hazaribagh",
    "u45": "Giridih",
    "u46": "Deoghar",
    "u47": "Dumka",
    "u48": "Jamshedpur",
    "u49": "Simdega",
    "u50": "Palamu",
    "u51": "Latehar",
    "u52": "Gumla",
    "u53": "Chaibasa",
    "u54": "Ranchi",
    "u55": "Dhanbad",
    "u56": "Bokaro",
    "u57": "Hazaribagh",
    "u58": "Giridih",
    "u59": "Deoghar",
    "u60": "Dumka",
    "u61": "Ranchi",
    "u62": "Dhanbad",
    "u63": "Bokaro",
    "u64": "Hazaribagh",
    "u65": "Giridih",
    "u66": "Deoghar",
    "u67": "Dumka",
    "u68": "Jamshedpur",
    "u69": "Simdega",
    "u70": "Palamu",
    "u71": "Latehar",
    "u72": "Gumla",
    "u73": "Chaibasa",
    "u74": "Ranchi",
    "u75": "Dhanbad",
    "u76": "Bokaro",
    "u77": "Hazaribagh",
    "u78": "Giridih",
    "u79": "Deoghar",
    "u80": "Dumka",
    "u81": "Ranchi",
    "u82": "Dhanbad",
    "u83": "Bokaro",
    "u84": "Hazaribagh",
    "u85": "Giridih",
    "u86": "Deoghar",
    "u87": "Dumka",
    "u88": "Jamshedpur",
    "u89": "Simdega",
    "u90": "Palamu",
    "u91": "Latehar",
    "u92": "Gumla",
    "u93": "Chaibasa",
    "u94": "Ranchi",
    "u95": "Dhanbad",
    "u96": "Bokaro",
    "u97": "Hazaribagh",
    "u98": "Giridih",
    "u99": "Deoghar",
    "u100": "Dumka",
  };
  
  const sites: Record<string, string[]> = {
    "Ranchi": ["Kanke Village", "Ratu Block", "Morabadi", "Harmu", "Kokra"],
    "Dhanbad": ["Jharia Town", "Govindpur", "Bhuli", "Katras", "Sijua"],
    "Bokaro": ["Sector 4", "Sector 12", "Jhapsali", "Chas", "Petarwar"],
    "Jamshedpur": ["Sakchi", "Bistupur", "Sonari", "Kadma", "Jugsalai"],
    "Hazaribagh": ["Ramgarh Road", "Centre Market", "Hasanpur", "Katkamdag", "Bishungarh"],
    "Giridih": ["Giridih Town", "Tisri", "Dhanwar", "Gawan", "Bagodar"],
    "Deoghar": ["Baba Dham", "Sapha", "Chandra Mohan", "Rohini", "Mohanpur"],
    "Dumka": ["Dumka Town", "Jama", "Shikaripara", "Raneshwar", "Masanjor"],
    "Simdega": ["Simdega Town", "Bano", "Kolebira", "Kurdeg", "Thethaitangar"],
    "Palamu": ["Daltonganj", "Latehar", "Barwadih", "Panki", "Satbarwa"],
    "Latehar": ["Latehar Town", "Balumath", "Barwadih", "Mahuadanr", "Chandwa"],
    "Gumla": ["Gumla Town", "Bishunpur", "Basia", "Ghaghra", "Chainpur"],
    "Chaibasa": ["Chaibasa Town", "Jharsuguda", "Rourkela", "Sundargarh", "Bonai"],
  };
  const deviceTypes = ["solar_pump", "rooftop_solar", "mini_grid", "high_mast", "street_light"];
  const contractors = ["Green Energy Solutions", "Solar Tech India", "NA", "Eco Power Systems", "Sunrise Energy"];
  const issues = [
    "Pump not working since morning. Motor makes unusual noise.",
    "Inverter showing error code E05. Power output reduced by 50%.",
    "Frequent power fluctuations affecting connected households.",
    "All lights not working. Complete failure.",
    "Request for capacity upgrade. Current system insufficient for village needs.",
    "Solar panels covered with dust and debris. Cleaning required.",
    "Battery not charging properly. Voltage dropping frequently.",
    "Connection wire damaged by animals. Immediate repair needed.",
    "Controller malfunctioning. Display showing wrong values.",
    "Water level sensor not working. Automatic switch failing.",
  ];
  const priorities: Array<"low" | "medium" | "high" | "critical"> = ["low", "medium", "high", "critical"];

  const tickets: CreateTicketData[] = [];
  const now = new Date();

  for (let i = 0; i < count; i++) {
    const userNum = Math.floor(Math.random() * 100) + 1;
    const userId = `u${userNum}`;
    const district = userDistrictMap[userId] || "Ranchi";
    const siteList = sites[district as keyof typeof sites] || [district];
    const site = siteList[Math.floor(Math.random() * siteList.length)];
    const daysAgo = Math.floor(Math.random() * 60);
    const createdDate = new Date(now);
    createdDate.setDate(createdDate.getDate() - daysAgo);
    
    const dueDate = new Date(createdDate);
    dueDate.setDate(dueDate.getDate() + Math.floor(Math.random() * 14) + 1);

    tickets.push({
      userId: userId,
      userName: `User${userNum}`,
      userMobile: `9876543${String(Math.floor(Math.random() * 1000)).padStart(4, '0')}`,
      userEmail: `user${userNum}@gmail.com`,
      district,
      site,
      dueDate: dueDate.toISOString().split('T')[0],
      issueDescription: `Ticket ${i + 1}: ${issues[Math.floor(Math.random() * issues.length)]}`,
      priority: priorities[Math.floor(Math.random() * priorities.length)],
      contractor: contractors[Math.floor(Math.random() * contractors.length)],
      deviceId: `d${Math.floor(Math.random() * 10) + 1}`,
      deviceType: deviceTypes[Math.floor(Math.random() * deviceTypes.length)],
    });
  }

  return tickets;
}
